create TABLE account_holder (
  holderid INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   firstname VARCHAR(20) NOT NULL,
   lastname VARCHAR(20) NOT NULL,
   email VARCHAR(20) NOT NULL,
   passcode VARCHAR(20) NOT NULL,
   accountnumber VARCHAR(20),
   savings_accountnumber VARCHAR(20),
   address VARCHAR(20) NOT NULL,
   CONSTRAINT pk_account_holder PRIMARY KEY (holderid)
);

create TABLE checking_transactions (
  transaction_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   amount INTEGER NOT NULL,
   merchant VARCHAR(20) NOT NULL,
   date_time VARCHAR(20),
   status VARCHAR(20) NOT NULL,
   CONSTRAINT pk_checking_transactions PRIMARY KEY (transaction_id)
);

create TABLE checkings_account (
  accountnumber VARCHAR(20) NOT NULL,
   balance INTEGER NOT NULL,
   transaction_id INTEGER NOT NULL,
   CONSTRAINT pk_checkings_account PRIMARY KEY (accountnumber)
);

create TABLE savings_account (
  savings_accountnumber VARCHAR(20) NOT NULL,
   balance INTEGER NOT NULL,
   transfer_id INTEGER NOT NULL,
   CONSTRAINT pk_savings_account PRIMARY KEY (savings_accountnumber)
);

create TABLE savings_transfers (
  transfer_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   amount INTEGER NOT NULL,
   recieving_accountnumber VARCHAR(20) NOT NULL,
   date_time VARCHAR(20),
   status VARCHAR(20) NOT NULL,
   CONSTRAINT pk_savings_transfers PRIMARY KEY (transfer_id)
);